### ISSUE TITLE
Add Orationi.Manager Project

### ISSUE THREAD

**Issue by KP0H** [Rankcore/Orationi#16]
That should be web-app based on last version of asp.net.

**Comment by KP0H** [comment]
Install ASP.NET 5 RC1 Update 1 
http://go.microsoft.com/fwlink/?LinkId=627627

**Comment by KP0H** [comment]
https://go.microsoft.com/fwlink/?LinkId=708515 - DotNetVersionManager

**Comment by KP0H** [comment]
https://go.microsoft.com/fwlink/?LinkId=708525

**Comment by kirill-kruchkov** [comment]
Please check https://github.com/Rankcore/Orationi/tree/dev_prototype/Orationi.Manager  README file

**Comment by KP0H** [comment]
@kirill-kruchkov which reason for change master API's binding and behavior to WebHttp?

**Comment by kirill-kruchkov** [comment]
@KP0H according to our conversation I changed API type from SOAP to REST so that we can provide easier way of communication for different types of clients. REST is more lightweight and, e. g., it's more natural for JS clients, which means we can make Orationi.Manager's UI more fluent and responsive.
